# Generated by Django 3.0.6 on 2020-06-09 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_useraddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='address',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='address2',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='address3',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='billing',
            field=models.BooleanField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='city',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='country',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='phone',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='shipping',
            field=models.BooleanField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='state',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='time_stamp',
            field=models.DateTimeField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='updated',
            field=models.DateTimeField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='zipcode',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
