# Generated by Django 3.0.6 on 2020-06-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200614_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='billing',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='shipping',
            field=models.BooleanField(default=1, max_length=120, null=True),
        ),
    ]
