# Generated by Django 3.0.7 on 2020-07-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200708_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='firstname',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='lastname',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
