# Generated by Django 3.0.6 on 2020-06-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200614_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='billing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='shipping',
            field=models.BooleanField(max_length=120, null=True),
        ),
    ]
