# Generated by Django 3.0.6 on 2020-06-10 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200609_1803'),
        ('users', '0003_auto_20200609_2123'),
    ]

    operations = [
    ]
