# Generated by Django 3.0.6 on 2020-06-10 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200609_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='address2',
            field=models.CharField(max_length=120),
        ),
    ]
