# Generated by Django 3.0.6 on 2020-06-10 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200610_0143'),
        ('users', '0004_merge_20200609_2142'),
    ]

    operations = [
    ]
