# Generated by Django 3.0.6 on 2020-06-14 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200614_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='address',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='address2',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='address3',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='billing',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='city',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='country',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='phone',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='shipping',
            field=models.BooleanField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='state',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='time_stamp',
            field=models.DateTimeField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='updated',
            field=models.DateTimeField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='zipcode',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
