# Generated by Django 3.0.6 on 2020-07-25 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200712_1510'),
        ('users', '0004_auto_20200724_2207'),
    ]

    operations = [
    ]
