# Generated by Django 3.0.6 on 2020-06-10 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200610_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='address2',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
