# Generated by Django 3.0.6 on 2020-06-11 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200610_2354'),
        ('users', '0005_auto_20200610_1445'),
    ]

    operations = [
    ]
