# Generated by Django 3.0.6 on 2020-06-11 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_merge_20200611_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='address2',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.DeleteModel(
            name='UserDefaultAddresses',
        ),
    ]
