# Generated by Django 3.0.6 on 2020-06-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='pennies_total',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=100000000),
        ),
    ]
