# Generated by Django 3.0.6 on 2020-06-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Raul', '0001_initial'),
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variation',
            field=models.ManyToManyField(blank=True, null=True, to='Raul.Variation'),
        ),
    ]
