# Generated by Django 3.0.6 on 2020-06-10 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_cart_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='items',
            new_name='cart_items',
        ),
    ]
