<<<<<<< HEAD
# Generated by Django 3.0.6 on 2020-07-09 02:42
=======
# Generated by Django 3.0.7 on 2020-07-29 14:50
>>>>>>> 08b1a766877b942bbc49d02ee423d8c17ed42b03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='')),
<<<<<<< HEAD
                ('category', models.CharField(choices=[('Plates', 'Plates'), ('Pot', 'Pot'), ('Flowers', 'Flowers'), ('Table', 'Table')], default='Plates', max_length=128)),
=======
                ('category', models.CharField(choices=[('Plates', 'Plates'), ('Pot', 'Pot'), ('Flowers', 'Flowers'), ('Table', 'Table'), ('Candlelight', 'Candlelight'), ('Decorative Objects', 'Decorative Objects'), ('Urns', 'Urns'), ('Vases & Cachepots', 'Vases & Cachepots'), ('Dinnerware', 'Dinnerware'), ('Pitchers', 'Pitchers'), ('Chairs', 'Chairs'), ('End Tables', 'End Tables'), ('Ottoman & Benches', 'Ottoman & Benches'), ('Outdoor Furniture', 'Outdoor Furniture'), ('ArtWork', 'ArtWork'), ('Mirrors', 'Mirrors'), ('All Sale Items', 'All Sale Items'), ('Bowls', 'Bowls'), ('Glasswear', 'Glasswear'), ('Vases and Cachepots', 'Vases and Cachepots'), ('Votives', 'Votives'), ('Wall Art', 'Wall Art')], max_length=128)),
                ('section', models.CharField(choices=[('Plates', 'Plates'), ('New Arrivals', 'New Arrivals'), ('Decorative Accessories', 'Decorative Accessories'), ('Furniture', 'Furniture'), ('Floral', 'Floral'), ('Tabletop', 'Tabletop'), ('Wall Art', 'Wall Art'), ('Sale', 'Sale')], max_length=128)),
>>>>>>> 08b1a766877b942bbc49d02ee423d8c17ed42b03
                ('slug', models.SlugField(null=True)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
<<<<<<< HEAD
            ],
        ),
        migrations.CreateModel(
            name='productimage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('active', models.BooleanField(default=True)),
                ('thumbnail', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Raul.product')),
=======
                ('imageFound', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
>>>>>>> 08b1a766877b942bbc49d02ee423d8c17ed42b03
            ],
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('size', 'size'), ('color', 'color'), ('package', 'package')], default='size', max_length=120)),
                ('title', models.CharField(max_length=120)),
<<<<<<< HEAD
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Raul.productimage')),
=======
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Raul.product')),
            ],
        ),
        migrations.CreateModel(
            name='productimage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('active', models.BooleanField(default=True)),
                ('thumbnail', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Raul.product')),
            ],
        ),
        migrations.CreateModel(
            name='FeatuedProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
>>>>>>> 08b1a766877b942bbc49d02ee423d8c17ed42b03
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Raul.product')),
            ],
        ),
    ]
