# Generated by Django 3.0.6 on 2020-06-04 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Raul', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.FileField(null=True, upload_to='raul_project/Raul/static.Raul/Images'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
