# Generated by Django 3.0.7 on 2020-07-29 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Raul', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Plates', 'Plates'), ('Pot', 'Pot'), ('Flowers', 'Flowers'), ('Table', 'Table'), ('Candlelight', 'Candlelight'), ('Decorative Objects', 'Decorative Objects'), ('Urns', 'Urns'), ('Vases & Cachepots', 'Vases & Cachepots'), ('Dinnerware', 'Dinnerware'), ('Pitchers', 'Pitchers'), ('Chairs', 'Chairs'), ('End Tables', 'End Tables'), ('Ottoman & Benches', 'Ottoman & Benches'), ('Outdoor Furniture', 'Outdoor Furniture'), ('ArtWork', 'ArtWork'), ('Mirrors', 'Mirrors'), ('All Sale Items', 'All Sale Items'), ('Bowls', 'Bowls'), ('Glasswear', 'Glasswear'), ('Vases and Cachepots', 'Vases and Cachepots'), ('Votives', 'Votives'), ('Wall Art', 'Wall Art'), ('Collection1', 'Collection1'), ('Collection2', 'Collection2')], max_length=128),
        ),
        migrations.AlterField(
            model_name='product',
            name='section',
            field=models.CharField(choices=[('Plates', 'Plates'), ('New Arrivals', 'New Arrivals'), ('Decorative Accessories', 'Decorative Accessories'), ('Furniture', 'Furniture'), ('Floral', 'Floral'), ('Tabletop', 'Tabletop'), ('Wall Art', 'Wall Art'), ('Sale', 'Sale'), ('Collection1', 'Collection1'), ('Collection2', 'Collection2')], max_length=128),
        ),
        migrations.CreateModel(
            name='LayoutView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Raul.product')),
            ],
        ),
        migrations.CreateModel(
            name='Collection2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Raul.product')),
            ],
        ),
        migrations.CreateModel(
            name='Collection1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Raul.product')),
            ],
        ),
    ]
