# Generated by Django 3.0.6 on 2020-06-04 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Raul', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
    ]
