# Generated by Django 3.0.7 on 2020-08-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Raul', '0002_auto_20200803_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Overweight',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='SuperOverweight',
            field=models.BooleanField(default=False),
        ),
    ]
