# Generated by Django 3.0.6 on 2020-06-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Raul', '0002_auto_20200624_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='section',
            field=models.CharField(choices=[('Plates', 'Plates'), ('Light', 'Light'), ('lights', 'lights')], default='New Arrivals', max_length=128),
        ),
    ]
