# Generated by Django 3.0.7 on 2020-07-30 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Raul', '0002_auto_20200729_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Plates', 'Plates'), ('Pot', 'Pot'), ('Flowers', 'Flowers'), ('Table', 'Table'), ('Candlelight', 'Candlelight'), ('Decorative Objects', 'Decorative Objects'), ('Urns', 'Urns'), ('Vases & Cachepots', 'Vases & Cachepots'), ('Dinnerware', 'Dinnerware'), ('Pitchers', 'Pitchers'), ('Chairs', 'Chairs'), ('End Tables', 'End Tables'), ('Ottoman & Benches', 'Ottoman & Benches'), ('Outdoor Furniture', 'Outdoor Furniture'), ('ArtWork', 'ArtWork'), ('Mirrors', 'Mirrors'), ('All Sale Items', 'All Sale Items'), ('Bowls', 'Bowls'), ('Glasswear', 'Glasswear'), ('Vases and Cachepots', 'Vases and Cachepots'), ('Votives', 'Votives'), ('Wall Art', 'Wall Art'), ('Rug Collection', 'Rug Collection'), ('Pot Collection', 'Pot Collection'), ('Layout Shop', 'Layout Shop')], max_length=128),
        ),
        migrations.AlterField(
            model_name='product',
            name='section',
            field=models.CharField(choices=[('Plates', 'Plates'), ('New Arrivals', 'New Arrivals'), ('Decorative Accessories', 'Decorative Accessories'), ('Furniture', 'Furniture'), ('Floral', 'Floral'), ('Tabletop', 'Tabletop'), ('Wall Art', 'Wall Art'), ('Sale', 'Sale'), ('Rug Collection', 'Rug Collection'), ('Pot Collection', 'Pot Collection'), ('Shopping The Layout', 'Shopping The Layout')], max_length=128),
        ),
    ]
