# Generated by Django 3.0.6 on 2020-06-04 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Raul', '0002_remove_product_images'),
        ('Raul', '0002_auto_20200604_0013'),
    ]

    operations = [
    ]
