# Generated by Django 3.0.6 on 2020-06-25 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Raul', '0003_auto_20200624_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
