# Generated by Django 3.0.6 on 2020-06-19 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Raul', '0003_auto_20200619_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='category',
            field=models.CharField(choices=[('size', 'size'), ('color', 'color'), ('package', 'package')], max_length=120),
        ),
    ]
