# Generated by Django 3.0.7 on 2020-07-12 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Raul', '0003_product_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Plates', 'Plates'), ('Pot', 'Pot'), ('Flowers', 'Flowers'), ('Table', 'Table')], max_length=128),
        ),
        migrations.AlterField(
            model_name='product',
            name='section',
            field=models.CharField(choices=[('Plates', 'Plates'), ('New Arrivals', 'New Arrivals'), ('Decorative Accessories', 'Decorative Accessories'), ('Furniture', 'Furniture'), ('Floral', 'Floral'), ('Tabletop', 'Tabletop'), ('Wall Art', 'Wall Art'), ('Sale', 'Sale')], max_length=128),
        ),
    ]
