# Generated by Django 3.0.6 on 2020-06-04 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Raul', '0004_auto_20200604_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
