# Generated by Django 3.0.6 on 2020-06-05 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Raul', '0004_auto_20200604_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
