# Generated by Django 3.0.6 on 2020-06-05 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Raul', '0005_auto_20200605_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='null', max_length=128),
        ),
    ]
