# Generated by Django 3.0.6 on 2020-06-23 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Raul', '0006_auto_20200622_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Plates', 'Plates'), ('Pot', 'Pot'), ('Flowers', 'Flowers')], default='Plates', max_length=128),
        ),
    ]
