# Generated by Django 3.0.6 on 2020-06-06 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Raul', '0006_auto_20200605_2141'),
        ('Raul', '0005_auto_20200604_2212'),
    ]

    operations = [
    ]
