# Generated by Django 3.0.6 on 2020-06-25 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_pdf',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
