# Generated by Django 3.0.7 on 2020-07-12 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_useraddress_default'),
        ('orders', '0002_stripeinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_address', to='users.BillingAddress'),
        ),
    ]
