# Generated by Django 3.0.7 on 2020-07-30 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200729_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Shipping',
            field=models.DecimalField(blank=True, decimal_places=2, default=9.0, max_digits=1000, max_length=120, null=True),
        ),
    ]
