# Generated by Django 3.0.7 on 2020-07-13 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200712_1810'),
        ('orders', '0003_auto_20200712_0411'),
    ]

    operations = [
    ]
