# Generated by Django 3.0.6 on 2020-06-10 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200609_1736'),
        ('orders', '0003_order_address'),
    ]

    operations = [
    ]
