# Generated by Django 3.0.6 on 2020-06-10 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_merge_20200609_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
    ]
