# Generated by Django 3.0.6 on 2020-06-10 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_address'),
        ('orders', '0004_merge_20200609_2142'),
    ]

    operations = [
    ]
