# Generated by Django 3.0.6 on 2020-06-11 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200611_2159'),
        ('orders', '0005_remove_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Billing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='USER_BILLING', to='users.UserAddress'),
        ),
        migrations.AddField(
            model_name='order',
            name='Shipping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='USER_SHIPPING', to='users.UserAddress'),
        ),
    ]
