# Generated by Django 3.0.6 on 2020-06-11 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200611_2159'),
        ('orders', '0006_auto_20200611_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Billing',
        ),
        migrations.AddField(
            model_name='order',
            name='Billing',
            field=models.ManyToManyField(blank=True, null=True, related_name='USER_BILLING', to='users.UserAddress'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='Shipping',
        ),
        migrations.AddField(
            model_name='order',
            name='Shipping',
            field=models.ManyToManyField(blank=True, null=True, related_name='USER_SHIPPING', to='users.UserAddress'),
        ),
    ]
