# Generated by Django 3.0.6 on 2020-06-14 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200614_1515'),
        ('orders', '0010_auto_20200614_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billing_address',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_address', to='users.UserAddress'),
        ),
        migrations.AlterField(
            model_name='order',
            name='final_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=1000.0, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, default='ABC', max_length=120, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_address', to='users.UserAddress'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('Started', 'Started'), ('Abandoned', 'Abandoned'), ('Finished', 'Finished')], default='Started', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='sub_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=1000.0, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=1000.0, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
