# Generated by Django 3.0.6 on 2020-06-15 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200615_0310'),
        ('orders', '0011_auto_20200614_1515'),
    ]

    operations = [
    ]
